In [26]:
from sklearn.datasets import load_iris
from sklearn.impute import SimpleImputer, MissingIndicator
from sklearn.model_selection import train_test_split
from sklearn.pipeline import FeatureUnion, make_pipeline
from sklearn.tree import DecisionTreeClassifier
X, y = load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
mask = np.random.randint(0, 2, size=X.shape).astype(bool)
mask

array([[ True,  True, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False],
       [ True, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False,  True],
       [False,  True,  True,  True],
       [False,  True, False,  True],
 

In [28]:
X[mask] = np.nan
X

array([[nan, nan, 1.4, 0.2],
       [nan, 3. , 1.4, nan],
       [nan, 3.2, nan, 0.2],
       [nan, 3.1, nan, 0.2],
       [5. , nan, nan, nan],
       [5.4, 3.9, nan, 0.4],
       [4.6, nan, nan, nan],
       [5. , 3.4, nan, nan],
       [4.4, nan, 1.4, nan],
       [nan, nan, nan, nan],
       [5.4, 3.7, nan, nan],
       [nan, nan, nan, nan],
       [4.8, nan, nan, 0.1],
       [nan, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [nan, nan, 1.5, 0.4],
       [nan, nan, 1.3, nan],
       [nan, 3.5, 1.4, 0.3],
       [nan, nan, 1.7, nan],
       [nan, 3.8, 1.5, nan],
       [5.4, 3.4, 1.7, nan],
       [5.1, 3.7, 1.5, 0.4],
       [nan, 3.6, 1. , 0.2],
       [nan, nan, nan, nan],
       [4.8, 3.4, 1.9, nan],
       [5. , nan, nan, nan],
       [5. , nan, 1.6, nan],
       [5.2, nan, nan, 0.2],
       [nan, nan, nan, nan],
       [nan, nan, 1.6, 0.2],
       [nan, nan, 1.6, 0.2],
       [5.4, nan, 1.5, nan],
       [nan, 4.1, nan, nan],
       [5.5, nan, nan, 0.2],
       [4.9, n

In [23]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
X_train, X_test, y_train, _ = train_test_split(X, y, test_size=100,
                                               random_state=0)

In [17]:
transformer = FeatureUnion(
    transformer_list=[
        ('features', SimpleImputer(strategy='mean')),
        ('indicators', MissingIndicator())])
transformer = transformer.fit(X_train, y_train)
results = transformer.transform(X_test)
results.shape

(100, 8)

In [18]:
results

array([[6.084     , 2.8       , 3.84347826, 1.26363636, 1.        ,
        0.        , 1.        , 1.        ],
       [6.        , 2.2       , 4.        , 1.        , 0.        ,
        0.        , 0.        , 0.        ],
       [6.084     , 4.2       , 1.4       , 1.26363636, 1.        ,
        0.        , 0.        , 1.        ],
       [7.3       , 2.9       , 6.3       , 1.8       , 0.        ,
        0.        , 0.        , 0.        ],
       [5.        , 3.13913043, 3.84347826, 0.2       , 0.        ,
        1.        , 1.        , 0.        ],
       [6.084     , 3.3       , 6.        , 1.26363636, 1.        ,
        0.        , 0.        , 1.        ],
       [6.084     , 3.13913043, 3.84347826, 0.3       , 1.        ,
        1.        , 1.        , 0.        ],
       [6.7       , 3.1       , 3.84347826, 1.5       , 0.        ,
        0.        , 1.        , 0.        ],
       [6.8       , 3.13913043, 3.84347826, 1.26363636, 0.        ,
        1.        , 1.      

In [30]:
transformer = FeatureUnion(
    transformer_list=[
        ('features', SimpleImputer(strategy='mean')),
        ('indicators', MissingIndicator())])
transformer = transformer.fit(X_train)
results = transformer.transform(X_train)
results.shape

(50, 8)

In [31]:
results

array([[6.008     , 3.        , 3.69583333, 0.2       , 1.        ,
        0.        , 1.        , 0.        ],
       [5.4       , 3.9       , 3.69583333, 0.4       , 0.        ,
        0.        , 1.        , 0.        ],
       [5.5       , 3.23809524, 3.69583333, 1.3       , 0.        ,
        1.        , 1.        , 0.        ],
       [6.8       , 3.23809524, 3.69583333, 2.3       , 0.        ,
        1.        , 1.        , 0.        ],
       [6.008     , 3.23809524, 3.69583333, 1.10869565, 1.        ,
        1.        , 1.        , 1.        ],
       [6.008     , 3.23809524, 1.4       , 0.2       , 1.        ,
        1.        , 0.        , 0.        ],
       [4.9       , 3.23809524, 3.69583333, 1.10869565, 0.        ,
        1.        , 1.        , 1.        ],
       [6.008     , 3.23809524, 3.69583333, 1.10869565, 1.        ,
        1.        , 1.        , 1.        ],
       [6.008     , 3.23809524, 3.69583333, 1.10869565, 1.        ,
        1.        , 1.      

In [11]:
from sklearn.impute import MissingIndicator
X = np.array([[-1, -1, 1, 3],
              [4, -1, 0, -1],
              [8, -1, 1, 0]])
indicator = MissingIndicator(missing_values=-1,features='all')
mask_missing_values_only = indicator.fit_transform(X)
mask_missing_values_only

array([[ True,  True, False, False],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [13]:
X=X.astype('float')
X[mask_missing_values_only] = np.nan
X

array([[nan, nan,  1.,  3.],
       [ 4., nan,  0., nan],
       [ 8., nan,  1.,  0.]])