In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics.pairwise import rbf_kernel
import pandas as pd
 
 
    X, y = load_iris(return_X_y=True)
    a = [1,2,3,4,5,6,7,8]
    b = [110,111]
    A = X[a]
    B = X[b]
    K = rbf_kernel(X=A,Y=B)
    print(K)
    c = [110]
    C = X[c]
    print(C)
    K = rbf_kernel(X=A,Y=C)
    print(K)


[[0.00757805 0.00603608]
 [0.00535353 0.00405624]
 [0.00704808 0.00561395]
 [0.00794669 0.00542086]
 [0.01915867 0.01212483]
 [0.00636144 0.00463092]
 [0.00982819 0.00711891]
 [0.00471267 0.00394621]]
[[6.5 3.2 5.1 2. ]]
[[0.00757805]
 [0.00535353]
 [0.00704808]
 [0.00794669]
 [0.01915867]
 [0.00636144]
 [0.00982819]
 [0.00471267]]


In [7]:
 rbf_kernel(A)

array([[1.        , 0.97775124, 0.97287468, 0.91164921, 0.74267258,
        0.93706746, 0.95599748, 0.93706746],
       [0.97775124, 1.        , 0.98511194, 0.93706746, 0.74453159,
        0.98265224, 0.95839047, 0.95361047],
       [0.97287468, 0.98511194, 1.        , 0.90032452, 0.71177032,
        0.97287468, 0.93941306, 0.97775124],
       [0.91164921, 0.93706746, 0.90032452, 1.        , 0.90937293,
        0.94885432, 0.9875778 , 0.80856032],
       [0.74267258, 0.74453159, 0.71177032, 0.90937293, 1.        ,
        0.78075022, 0.8847059 , 0.5871353 ],
       [0.93706746, 0.98265224, 0.97287468, 0.94885432, 0.78075022,
        1.        , 0.95599748, 0.92774349],
       [0.95599748, 0.95839047, 0.93941306, 0.9875778 , 0.8847059 ,
        0.95599748, 1.        , 0.85641518],
       [0.93706746, 0.95361047, 0.97775124, 0.80856032, 0.5871353 ,
        0.92774349, 0.85641518, 1.        ]])

In [8]:
rbf_kernel(B)

array([[1.        , 0.92542702],
       [0.92542702, 1.        ]])

In [2]:
A

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2]])

In [12]:
asum=np.sum(A,1)
np.sum(A,1)

array([ 9.5,  9.4,  9.4, 10.2, 11.4,  9.7, 10.1,  8.9])

In [13]:
np.diag(asum)

array([[ 9.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  9.4,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  9.4,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , 10.2,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. , 11.4,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  9.7,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. , 10.1,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  8.9]])

In [16]:
in_arr = [2., 3., 8.] 
print ("Input array : ", in_arr) 
    
out_arr = np.reciprocal(in_arr) 
print ("Output array : ", out_arr) 

Input array :  [2.0, 3.0, 8.0]
Output array :  [0.5        0.33333333 0.125     ]


In [15]:
np.reciprocal(np.sqrt(asum))

array([0.32444284, 0.32616404, 0.32616404, 0.31311215, 0.29617444,
       0.32108065, 0.31465839, 0.33520076])

In [24]:
d = [10,121,62]
D=X[d]
D

array([[5.4, 3.7, 1.5, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [6. , 2.2, 4. , 1. ]])

In [25]:
similarity=rbf_kernel(D)
adjacency=similarity
similarity

array([[1.        , 0.01999046, 0.09301449],
       [0.01999046, 1.        , 0.55850037],
       [0.09301449, 0.55850037, 1.        ]])

In [26]:
degree_vector=np.sum(adjacency,1) #按行累加
degree_vector

array([1.11300495, 1.57849083, 1.65151486])

In [28]:
degree=np.diag(degree_vector)
degree

array([[1.11300495, 0.        , 0.        ],
       [0.        , 1.57849083, 0.        ],
       [0.        , 0.        , 1.65151486]])

In [29]:
laplacian=degree-adjacency
laplacian

array([[ 0.11300495, -0.01999046, -0.09301449],
       [-0.01999046,  0.57849083, -0.55850037],
       [-0.09301449, -0.55850037,  0.65151486]])

In [30]:
normaliser_vector=np.reciprocal(np.sqrt(degree_vector))
normaliser_vector

array([0.94787584, 0.7959375 , 0.77814182])

In [31]:
normaliser=np.diag(normaliser_vector)
normaliser

array([[0.94787584, 0.        , 0.        ],
       [0.        , 0.7959375 , 0.        ],
       [0.        , 0.        , 0.77814182]])

In [32]:
normaliser.dot(laplacian)

array([[ 0.10711466, -0.01894848, -0.08816619],
       [-0.01591116,  0.46044255, -0.44453139],
       [-0.07237846, -0.43459249,  0.50697096]])

In [33]:
np.dot(normaliser,laplacian)

array([[ 0.10711466, -0.01894848, -0.08816619],
       [-0.01591116,  0.46044255, -0.44453139],
       [-0.07237846, -0.43459249,  0.50697096]])

In [3]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-4, 5, 1)
y = np.array((x >= -2) & (x <= 2), dtype='int')

In [4]:
x

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [5]:
y

array([0, 0, 1, 1, 1, 1, 1, 0, 0])

In [6]:
x[y==0]

array([-4, -3,  3,  4])